package cn.com.fangself.generator.mybatis.model.dao;

import cn.com.fangself.generator.mybatis.model.pojo.Admin;
import cn.com.fangself.generator.mybatis.model.pojo.AdminExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface AdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_Admin
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    long countByExample(AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_Admin
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    int deleteByExample(AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_Admin
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer adminid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_Admin
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    int insert(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_Admin
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    int insertSelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_Admin
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    List<Admin> selectByExample(AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_Admin
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    Admin selectByPrimaryKey(Integer adminid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_Admin
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") Admin record, @Param("example") AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_Admin
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    int updateByExample(@Param("record") Admin record, @Param("example") AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_Admin
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_Admin
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    int updateByPrimaryKey(Admin record);
}