package cn.com.fangself.generator.mybatis.model.dao;

import cn.com.fangself.generator.mybatis.model.pojo.BuyInfo;
import cn.com.fangself.generator.mybatis.model.pojo.BuyInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BuyInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_BuyInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    long countByExample(BuyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_BuyInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    int deleteByExample(BuyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_BuyInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer buyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_BuyInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    int insert(BuyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_BuyInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    int insertSelective(BuyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_BuyInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    List<BuyInfo> selectByExample(BuyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_BuyInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    BuyInfo selectByPrimaryKey(Integer buyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_BuyInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") BuyInfo record, @Param("example") BuyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_BuyInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    int updateByExample(@Param("record") BuyInfo record, @Param("example") BuyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_BuyInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(BuyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_BuyInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    int updateByPrimaryKey(BuyInfo record);
}