package cn.com.fangself.generator.mybatis.model.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.com.fangself.generator.mybatis.model.pojo.GoodsInfo;
import cn.com.fangself.generator.mybatis.model.pojo.GoodsInfoExample;
import cn.com.fangself.model.pager.GoodsInfoPager;
import cn.com.fangself.model.to.queryto.GoodsInfoQueryTo;

public interface GoodsInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_GoodsInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    long countByExample(GoodsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_GoodsInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    int deleteByExample(GoodsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_GoodsInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer goodsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_GoodsInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    int insert(GoodsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_GoodsInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    int insertSelective(GoodsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_GoodsInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    List<GoodsInfo> selectByExampleWithBLOBs(GoodsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_GoodsInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    List<GoodsInfo> selectByExample(GoodsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_GoodsInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    GoodsInfo selectByPrimaryKey(Integer goodsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_GoodsInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") GoodsInfo record, @Param("example") GoodsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_GoodsInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    int updateByExampleWithBLOBs(@Param("record") GoodsInfo record, @Param("example") GoodsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_GoodsInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    int updateByExample(@Param("record") GoodsInfo record, @Param("example") GoodsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_GoodsInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(GoodsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_GoodsInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    int updateByPrimaryKeyWithBLOBs(GoodsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_GoodsInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    
    int updateByPrimaryKey(GoodsInfo record);
    /**
     * 自定义综合查询：得到所有的商品
     * @return List<GoodsInfoQueryTo>
     */
   
    List<GoodsInfoQueryTo> showAllGoodsOfRepo();
    
    /**
     * 通过指定的ID范围查询商品
     * 
     * */
    List<GoodsInfoQueryTo> showProductsByRange(GoodsInfoPager goodsInfoPager);
    
}