package cn.com.fangself.generator.mybatis.model.dao;

import cn.com.fangself.generator.mybatis.model.pojo.ShopCart;
import cn.com.fangself.generator.mybatis.model.pojo.ShopCartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ShopCart
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    long countByExample(ShopCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ShopCart
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    int deleteByExample(ShopCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ShopCart
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer cartid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ShopCart
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    int insert(ShopCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ShopCart
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    int insertSelective(ShopCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ShopCart
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    List<ShopCart> selectByExample(ShopCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ShopCart
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    ShopCart selectByPrimaryKey(Integer cartid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ShopCart
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") ShopCart record, @Param("example") ShopCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ShopCart
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    int updateByExample(@Param("record") ShopCart record, @Param("example") ShopCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ShopCart
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(ShopCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ShopCart
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    int updateByPrimaryKey(ShopCart record);
}