package cn.com.fangself.generator.mybatis.model.pojo;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_Admin.adminid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    private Integer adminid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_Admin.adminuuid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    private String adminuuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_Admin.adminpassword
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    private String adminpassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_Admin.adminid
     *
     * @return the value of tb_Admin.adminid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public Integer getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_Admin.adminid
     *
     * @param adminid the value for tb_Admin.adminid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setAdminid(Integer adminid) {
        this.adminid = adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_Admin.adminuuid
     *
     * @return the value of tb_Admin.adminuuid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public String getAdminuuid() {
        return adminuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_Admin.adminuuid
     *
     * @param adminuuid the value for tb_Admin.adminuuid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setAdminuuid(String adminuuid) {
        this.adminuuid = adminuuid == null ? null : adminuuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_Admin.adminpassword
     *
     * @return the value of tb_Admin.adminpassword
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public String getAdminpassword() {
        return adminpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_Admin.adminpassword
     *
     * @param adminpassword the value for tb_Admin.adminpassword
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setAdminpassword(String adminpassword) {
        this.adminpassword = adminpassword == null ? null : adminpassword.trim();
    }
}