package cn.com.fangself.generator.mybatis.model.pojo;

public class BuyInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_BuyInfo.buyid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    private Integer buyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_BuyInfo.buyuuid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    private String buyuuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_BuyInfo.goodsid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    private Integer goodsid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_BuyInfo.buyid
     *
     * @return the value of tb_BuyInfo.buyid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public Integer getBuyid() {
        return buyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_BuyInfo.buyid
     *
     * @param buyid the value for tb_BuyInfo.buyid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setBuyid(Integer buyid) {
        this.buyid = buyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_BuyInfo.buyuuid
     *
     * @return the value of tb_BuyInfo.buyuuid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public String getBuyuuid() {
        return buyuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_BuyInfo.buyuuid
     *
     * @param buyuuid the value for tb_BuyInfo.buyuuid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setBuyuuid(String buyuuid) {
        this.buyuuid = buyuuid == null ? null : buyuuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_BuyInfo.goodsid
     *
     * @return the value of tb_BuyInfo.goodsid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_BuyInfo.goodsid
     *
     * @param goodsid the value for tb_BuyInfo.goodsid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }
}