package cn.com.fangself.generator.mybatis.model.pojo;

public class GoodsInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_GoodsInfo.goodsid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    private Integer goodsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_GoodsInfo.goodsuuid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    private String goodsuuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_GoodsInfo.goodsbrand
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    private String goodsbrand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_GoodsInfo.goodsprice
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    private Double goodsprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_GoodsInfo.goodsurl
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    private String goodsurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_GoodsInfo.goodsdescript
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    private String goodsdescript;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_GoodsInfo.goodsid
     *
     * @return the value of tb_GoodsInfo.goodsid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_GoodsInfo.goodsid
     *
     * @param goodsid the value for tb_GoodsInfo.goodsid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_GoodsInfo.goodsuuid
     *
     * @return the value of tb_GoodsInfo.goodsuuid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public String getGoodsuuid() {
        return goodsuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_GoodsInfo.goodsuuid
     *
     * @param goodsuuid the value for tb_GoodsInfo.goodsuuid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setGoodsuuid(String goodsuuid) {
        this.goodsuuid = goodsuuid == null ? null : goodsuuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_GoodsInfo.goodsbrand
     *
     * @return the value of tb_GoodsInfo.goodsbrand
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public String getGoodsbrand() {
        return goodsbrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_GoodsInfo.goodsbrand
     *
     * @param goodsbrand the value for tb_GoodsInfo.goodsbrand
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setGoodsbrand(String goodsbrand) {
        this.goodsbrand = goodsbrand == null ? null : goodsbrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_GoodsInfo.goodsprice
     *
     * @return the value of tb_GoodsInfo.goodsprice
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public Double getGoodsprice() {
        return goodsprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_GoodsInfo.goodsprice
     *
     * @param goodsprice the value for tb_GoodsInfo.goodsprice
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setGoodsprice(Double goodsprice) {
        this.goodsprice = goodsprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_GoodsInfo.goodsurl
     *
     * @return the value of tb_GoodsInfo.goodsurl
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public String getGoodsurl() {
        return goodsurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_GoodsInfo.goodsurl
     *
     * @param goodsurl the value for tb_GoodsInfo.goodsurl
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setGoodsurl(String goodsurl) {
        this.goodsurl = goodsurl == null ? null : goodsurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_GoodsInfo.goodsdescript
     *
     * @return the value of tb_GoodsInfo.goodsdescript
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public String getGoodsdescript() {
        return goodsdescript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_GoodsInfo.goodsdescript
     *
     * @param goodsdescript the value for tb_GoodsInfo.goodsdescript
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setGoodsdescript(String goodsdescript) {
        this.goodsdescript = goodsdescript == null ? null : goodsdescript.trim();
    }
}