package cn.com.fangself.generator.mybatis.model.pojo;

import java.util.ArrayList;
import java.util.List;

public class GoodsInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_GoodsInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_GoodsInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_GoodsInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_GoodsInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public GoodsInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_GoodsInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_GoodsInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_GoodsInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_GoodsInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_GoodsInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_GoodsInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_GoodsInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_GoodsInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_GoodsInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_GoodsInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_GoodsInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGoodsidIsNull() {
            addCriterion("goodsid is null");
            return (Criteria) this;
        }

        public Criteria andGoodsidIsNotNull() {
            addCriterion("goodsid is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsidEqualTo(Integer value) {
            addCriterion("goodsid =", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidNotEqualTo(Integer value) {
            addCriterion("goodsid <>", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidGreaterThan(Integer value) {
            addCriterion("goodsid >", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidGreaterThanOrEqualTo(Integer value) {
            addCriterion("goodsid >=", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidLessThan(Integer value) {
            addCriterion("goodsid <", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidLessThanOrEqualTo(Integer value) {
            addCriterion("goodsid <=", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidIn(List<Integer> values) {
            addCriterion("goodsid in", values, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidNotIn(List<Integer> values) {
            addCriterion("goodsid not in", values, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidBetween(Integer value1, Integer value2) {
            addCriterion("goodsid between", value1, value2, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidNotBetween(Integer value1, Integer value2) {
            addCriterion("goodsid not between", value1, value2, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsuuidIsNull() {
            addCriterion("goodsuuid is null");
            return (Criteria) this;
        }

        public Criteria andGoodsuuidIsNotNull() {
            addCriterion("goodsuuid is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsuuidEqualTo(String value) {
            addCriterion("goodsuuid =", value, "goodsuuid");
            return (Criteria) this;
        }

        public Criteria andGoodsuuidNotEqualTo(String value) {
            addCriterion("goodsuuid <>", value, "goodsuuid");
            return (Criteria) this;
        }

        public Criteria andGoodsuuidGreaterThan(String value) {
            addCriterion("goodsuuid >", value, "goodsuuid");
            return (Criteria) this;
        }

        public Criteria andGoodsuuidGreaterThanOrEqualTo(String value) {
            addCriterion("goodsuuid >=", value, "goodsuuid");
            return (Criteria) this;
        }

        public Criteria andGoodsuuidLessThan(String value) {
            addCriterion("goodsuuid <", value, "goodsuuid");
            return (Criteria) this;
        }

        public Criteria andGoodsuuidLessThanOrEqualTo(String value) {
            addCriterion("goodsuuid <=", value, "goodsuuid");
            return (Criteria) this;
        }

        public Criteria andGoodsuuidLike(String value) {
            addCriterion("goodsuuid like", value, "goodsuuid");
            return (Criteria) this;
        }

        public Criteria andGoodsuuidNotLike(String value) {
            addCriterion("goodsuuid not like", value, "goodsuuid");
            return (Criteria) this;
        }

        public Criteria andGoodsuuidIn(List<String> values) {
            addCriterion("goodsuuid in", values, "goodsuuid");
            return (Criteria) this;
        }

        public Criteria andGoodsuuidNotIn(List<String> values) {
            addCriterion("goodsuuid not in", values, "goodsuuid");
            return (Criteria) this;
        }

        public Criteria andGoodsuuidBetween(String value1, String value2) {
            addCriterion("goodsuuid between", value1, value2, "goodsuuid");
            return (Criteria) this;
        }

        public Criteria andGoodsuuidNotBetween(String value1, String value2) {
            addCriterion("goodsuuid not between", value1, value2, "goodsuuid");
            return (Criteria) this;
        }

        public Criteria andGoodsbrandIsNull() {
            addCriterion("goodsbrand is null");
            return (Criteria) this;
        }

        public Criteria andGoodsbrandIsNotNull() {
            addCriterion("goodsbrand is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsbrandEqualTo(String value) {
            addCriterion("goodsbrand =", value, "goodsbrand");
            return (Criteria) this;
        }

        public Criteria andGoodsbrandNotEqualTo(String value) {
            addCriterion("goodsbrand <>", value, "goodsbrand");
            return (Criteria) this;
        }

        public Criteria andGoodsbrandGreaterThan(String value) {
            addCriterion("goodsbrand >", value, "goodsbrand");
            return (Criteria) this;
        }

        public Criteria andGoodsbrandGreaterThanOrEqualTo(String value) {
            addCriterion("goodsbrand >=", value, "goodsbrand");
            return (Criteria) this;
        }

        public Criteria andGoodsbrandLessThan(String value) {
            addCriterion("goodsbrand <", value, "goodsbrand");
            return (Criteria) this;
        }

        public Criteria andGoodsbrandLessThanOrEqualTo(String value) {
            addCriterion("goodsbrand <=", value, "goodsbrand");
            return (Criteria) this;
        }

        public Criteria andGoodsbrandLike(String value) {
            addCriterion("goodsbrand like", value, "goodsbrand");
            return (Criteria) this;
        }

        public Criteria andGoodsbrandNotLike(String value) {
            addCriterion("goodsbrand not like", value, "goodsbrand");
            return (Criteria) this;
        }

        public Criteria andGoodsbrandIn(List<String> values) {
            addCriterion("goodsbrand in", values, "goodsbrand");
            return (Criteria) this;
        }

        public Criteria andGoodsbrandNotIn(List<String> values) {
            addCriterion("goodsbrand not in", values, "goodsbrand");
            return (Criteria) this;
        }

        public Criteria andGoodsbrandBetween(String value1, String value2) {
            addCriterion("goodsbrand between", value1, value2, "goodsbrand");
            return (Criteria) this;
        }

        public Criteria andGoodsbrandNotBetween(String value1, String value2) {
            addCriterion("goodsbrand not between", value1, value2, "goodsbrand");
            return (Criteria) this;
        }

        public Criteria andGoodspriceIsNull() {
            addCriterion("goodsprice is null");
            return (Criteria) this;
        }

        public Criteria andGoodspriceIsNotNull() {
            addCriterion("goodsprice is not null");
            return (Criteria) this;
        }

        public Criteria andGoodspriceEqualTo(Double value) {
            addCriterion("goodsprice =", value, "goodsprice");
            return (Criteria) this;
        }

        public Criteria andGoodspriceNotEqualTo(Double value) {
            addCriterion("goodsprice <>", value, "goodsprice");
            return (Criteria) this;
        }

        public Criteria andGoodspriceGreaterThan(Double value) {
            addCriterion("goodsprice >", value, "goodsprice");
            return (Criteria) this;
        }

        public Criteria andGoodspriceGreaterThanOrEqualTo(Double value) {
            addCriterion("goodsprice >=", value, "goodsprice");
            return (Criteria) this;
        }

        public Criteria andGoodspriceLessThan(Double value) {
            addCriterion("goodsprice <", value, "goodsprice");
            return (Criteria) this;
        }

        public Criteria andGoodspriceLessThanOrEqualTo(Double value) {
            addCriterion("goodsprice <=", value, "goodsprice");
            return (Criteria) this;
        }

        public Criteria andGoodspriceIn(List<Double> values) {
            addCriterion("goodsprice in", values, "goodsprice");
            return (Criteria) this;
        }

        public Criteria andGoodspriceNotIn(List<Double> values) {
            addCriterion("goodsprice not in", values, "goodsprice");
            return (Criteria) this;
        }

        public Criteria andGoodspriceBetween(Double value1, Double value2) {
            addCriterion("goodsprice between", value1, value2, "goodsprice");
            return (Criteria) this;
        }

        public Criteria andGoodspriceNotBetween(Double value1, Double value2) {
            addCriterion("goodsprice not between", value1, value2, "goodsprice");
            return (Criteria) this;
        }

        public Criteria andGoodsurlIsNull() {
            addCriterion("goodsurl is null");
            return (Criteria) this;
        }

        public Criteria andGoodsurlIsNotNull() {
            addCriterion("goodsurl is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsurlEqualTo(String value) {
            addCriterion("goodsurl =", value, "goodsurl");
            return (Criteria) this;
        }

        public Criteria andGoodsurlNotEqualTo(String value) {
            addCriterion("goodsurl <>", value, "goodsurl");
            return (Criteria) this;
        }

        public Criteria andGoodsurlGreaterThan(String value) {
            addCriterion("goodsurl >", value, "goodsurl");
            return (Criteria) this;
        }

        public Criteria andGoodsurlGreaterThanOrEqualTo(String value) {
            addCriterion("goodsurl >=", value, "goodsurl");
            return (Criteria) this;
        }

        public Criteria andGoodsurlLessThan(String value) {
            addCriterion("goodsurl <", value, "goodsurl");
            return (Criteria) this;
        }

        public Criteria andGoodsurlLessThanOrEqualTo(String value) {
            addCriterion("goodsurl <=", value, "goodsurl");
            return (Criteria) this;
        }

        public Criteria andGoodsurlLike(String value) {
            addCriterion("goodsurl like", value, "goodsurl");
            return (Criteria) this;
        }

        public Criteria andGoodsurlNotLike(String value) {
            addCriterion("goodsurl not like", value, "goodsurl");
            return (Criteria) this;
        }

        public Criteria andGoodsurlIn(List<String> values) {
            addCriterion("goodsurl in", values, "goodsurl");
            return (Criteria) this;
        }

        public Criteria andGoodsurlNotIn(List<String> values) {
            addCriterion("goodsurl not in", values, "goodsurl");
            return (Criteria) this;
        }

        public Criteria andGoodsurlBetween(String value1, String value2) {
            addCriterion("goodsurl between", value1, value2, "goodsurl");
            return (Criteria) this;
        }

        public Criteria andGoodsurlNotBetween(String value1, String value2) {
            addCriterion("goodsurl not between", value1, value2, "goodsurl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_GoodsInfo
     *
     * @mbg.generated do_not_delete_during_merge Mon May 29 15:39:24 GMT+08:00 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_GoodsInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}