package cn.com.fangself.generator.mybatis.model.pojo;

public class Member {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_Member.memberid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    private Integer memberid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_Member.memberuuid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    private String memberuuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_Member.username
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_Member.userpwd
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    private String userpwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_Member.email
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_Member.phonenum
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    private String phonenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_Member.sex
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_Member.realname
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_Member.address
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_Member.postcode
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    private String postcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_Member.memberid
     *
     * @return the value of tb_Member.memberid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public Integer getMemberid() {
        return memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_Member.memberid
     *
     * @param memberid the value for tb_Member.memberid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setMemberid(Integer memberid) {
        this.memberid = memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_Member.memberuuid
     *
     * @return the value of tb_Member.memberuuid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public String getMemberuuid() {
        return memberuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_Member.memberuuid
     *
     * @param memberuuid the value for tb_Member.memberuuid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setMemberuuid(String memberuuid) {
        this.memberuuid = memberuuid == null ? null : memberuuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_Member.username
     *
     * @return the value of tb_Member.username
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_Member.username
     *
     * @param username the value for tb_Member.username
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_Member.userpwd
     *
     * @return the value of tb_Member.userpwd
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public String getUserpwd() {
        return userpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_Member.userpwd
     *
     * @param userpwd the value for tb_Member.userpwd
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setUserpwd(String userpwd) {
        this.userpwd = userpwd == null ? null : userpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_Member.email
     *
     * @return the value of tb_Member.email
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_Member.email
     *
     * @param email the value for tb_Member.email
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_Member.phonenum
     *
     * @return the value of tb_Member.phonenum
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public String getPhonenum() {
        return phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_Member.phonenum
     *
     * @param phonenum the value for tb_Member.phonenum
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setPhonenum(String phonenum) {
        this.phonenum = phonenum == null ? null : phonenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_Member.sex
     *
     * @return the value of tb_Member.sex
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_Member.sex
     *
     * @param sex the value for tb_Member.sex
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_Member.realname
     *
     * @return the value of tb_Member.realname
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_Member.realname
     *
     * @param realname the value for tb_Member.realname
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_Member.address
     *
     * @return the value of tb_Member.address
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_Member.address
     *
     * @param address the value for tb_Member.address
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_Member.postcode
     *
     * @return the value of tb_Member.postcode
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_Member.postcode
     *
     * @param postcode the value for tb_Member.postcode
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode == null ? null : postcode.trim();
    }
}