package cn.com.fangself.generator.mybatis.model.pojo;

import java.util.Date;

public class OrderInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_OrderInfo.orderid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    private Integer orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_OrderInfo.orderuuid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    private String orderuuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_OrderInfo.memberid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    private Integer memberid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_OrderInfo.orderdate
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    private Date orderdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_OrderInfo.receviername
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    private String receviername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_OrderInfo.recevierphone
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    private String recevierphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_OrderInfo.receiveraddress
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    private String receiveraddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_OrderInfo.receiverpostcode
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    private String receiverpostcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_OrderInfo.receiveremails
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    private String receiveremails;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_OrderInfo.isconfirm
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    private Byte isconfirm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_OrderInfo.ispayment
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    private Byte ispayment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_OrderInfo.orderid
     *
     * @return the value of tb_OrderInfo.orderid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_OrderInfo.orderid
     *
     * @param orderid the value for tb_OrderInfo.orderid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_OrderInfo.orderuuid
     *
     * @return the value of tb_OrderInfo.orderuuid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public String getOrderuuid() {
        return orderuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_OrderInfo.orderuuid
     *
     * @param orderuuid the value for tb_OrderInfo.orderuuid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setOrderuuid(String orderuuid) {
        this.orderuuid = orderuuid == null ? null : orderuuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_OrderInfo.memberid
     *
     * @return the value of tb_OrderInfo.memberid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public Integer getMemberid() {
        return memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_OrderInfo.memberid
     *
     * @param memberid the value for tb_OrderInfo.memberid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setMemberid(Integer memberid) {
        this.memberid = memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_OrderInfo.orderdate
     *
     * @return the value of tb_OrderInfo.orderdate
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public Date getOrderdate() {
        return orderdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_OrderInfo.orderdate
     *
     * @param orderdate the value for tb_OrderInfo.orderdate
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setOrderdate(Date orderdate) {
        this.orderdate = orderdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_OrderInfo.receviername
     *
     * @return the value of tb_OrderInfo.receviername
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public String getReceviername() {
        return receviername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_OrderInfo.receviername
     *
     * @param receviername the value for tb_OrderInfo.receviername
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setReceviername(String receviername) {
        this.receviername = receviername == null ? null : receviername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_OrderInfo.recevierphone
     *
     * @return the value of tb_OrderInfo.recevierphone
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public String getRecevierphone() {
        return recevierphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_OrderInfo.recevierphone
     *
     * @param recevierphone the value for tb_OrderInfo.recevierphone
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setRecevierphone(String recevierphone) {
        this.recevierphone = recevierphone == null ? null : recevierphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_OrderInfo.receiveraddress
     *
     * @return the value of tb_OrderInfo.receiveraddress
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public String getReceiveraddress() {
        return receiveraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_OrderInfo.receiveraddress
     *
     * @param receiveraddress the value for tb_OrderInfo.receiveraddress
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setReceiveraddress(String receiveraddress) {
        this.receiveraddress = receiveraddress == null ? null : receiveraddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_OrderInfo.receiverpostcode
     *
     * @return the value of tb_OrderInfo.receiverpostcode
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public String getReceiverpostcode() {
        return receiverpostcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_OrderInfo.receiverpostcode
     *
     * @param receiverpostcode the value for tb_OrderInfo.receiverpostcode
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setReceiverpostcode(String receiverpostcode) {
        this.receiverpostcode = receiverpostcode == null ? null : receiverpostcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_OrderInfo.receiveremails
     *
     * @return the value of tb_OrderInfo.receiveremails
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public String getReceiveremails() {
        return receiveremails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_OrderInfo.receiveremails
     *
     * @param receiveremails the value for tb_OrderInfo.receiveremails
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setReceiveremails(String receiveremails) {
        this.receiveremails = receiveremails == null ? null : receiveremails.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_OrderInfo.isconfirm
     *
     * @return the value of tb_OrderInfo.isconfirm
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public Byte getIsconfirm() {
        return isconfirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_OrderInfo.isconfirm
     *
     * @param isconfirm the value for tb_OrderInfo.isconfirm
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setIsconfirm(Byte isconfirm) {
        this.isconfirm = isconfirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_OrderInfo.ispayment
     *
     * @return the value of tb_OrderInfo.ispayment
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public Byte getIspayment() {
        return ispayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_OrderInfo.ispayment
     *
     * @param ispayment the value for tb_OrderInfo.ispayment
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setIspayment(Byte ispayment) {
        this.ispayment = ispayment;
    }
}