package cn.com.fangself.generator.mybatis.model.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class OrderInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_OrderInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_OrderInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_OrderInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_OrderInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public OrderInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_OrderInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_OrderInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_OrderInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_OrderInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_OrderInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_OrderInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_OrderInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_OrderInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_OrderInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_OrderInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_OrderInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andOrderidIsNull() {
            addCriterion("orderid is null");
            return (Criteria) this;
        }

        public Criteria andOrderidIsNotNull() {
            addCriterion("orderid is not null");
            return (Criteria) this;
        }

        public Criteria andOrderidEqualTo(Integer value) {
            addCriterion("orderid =", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotEqualTo(Integer value) {
            addCriterion("orderid <>", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThan(Integer value) {
            addCriterion("orderid >", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThanOrEqualTo(Integer value) {
            addCriterion("orderid >=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThan(Integer value) {
            addCriterion("orderid <", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThanOrEqualTo(Integer value) {
            addCriterion("orderid <=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidIn(List<Integer> values) {
            addCriterion("orderid in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotIn(List<Integer> values) {
            addCriterion("orderid not in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidBetween(Integer value1, Integer value2) {
            addCriterion("orderid between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotBetween(Integer value1, Integer value2) {
            addCriterion("orderid not between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderuuidIsNull() {
            addCriterion("orderuuid is null");
            return (Criteria) this;
        }

        public Criteria andOrderuuidIsNotNull() {
            addCriterion("orderuuid is not null");
            return (Criteria) this;
        }

        public Criteria andOrderuuidEqualTo(String value) {
            addCriterion("orderuuid =", value, "orderuuid");
            return (Criteria) this;
        }

        public Criteria andOrderuuidNotEqualTo(String value) {
            addCriterion("orderuuid <>", value, "orderuuid");
            return (Criteria) this;
        }

        public Criteria andOrderuuidGreaterThan(String value) {
            addCriterion("orderuuid >", value, "orderuuid");
            return (Criteria) this;
        }

        public Criteria andOrderuuidGreaterThanOrEqualTo(String value) {
            addCriterion("orderuuid >=", value, "orderuuid");
            return (Criteria) this;
        }

        public Criteria andOrderuuidLessThan(String value) {
            addCriterion("orderuuid <", value, "orderuuid");
            return (Criteria) this;
        }

        public Criteria andOrderuuidLessThanOrEqualTo(String value) {
            addCriterion("orderuuid <=", value, "orderuuid");
            return (Criteria) this;
        }

        public Criteria andOrderuuidLike(String value) {
            addCriterion("orderuuid like", value, "orderuuid");
            return (Criteria) this;
        }

        public Criteria andOrderuuidNotLike(String value) {
            addCriterion("orderuuid not like", value, "orderuuid");
            return (Criteria) this;
        }

        public Criteria andOrderuuidIn(List<String> values) {
            addCriterion("orderuuid in", values, "orderuuid");
            return (Criteria) this;
        }

        public Criteria andOrderuuidNotIn(List<String> values) {
            addCriterion("orderuuid not in", values, "orderuuid");
            return (Criteria) this;
        }

        public Criteria andOrderuuidBetween(String value1, String value2) {
            addCriterion("orderuuid between", value1, value2, "orderuuid");
            return (Criteria) this;
        }

        public Criteria andOrderuuidNotBetween(String value1, String value2) {
            addCriterion("orderuuid not between", value1, value2, "orderuuid");
            return (Criteria) this;
        }

        public Criteria andMemberidIsNull() {
            addCriterion("memberid is null");
            return (Criteria) this;
        }

        public Criteria andMemberidIsNotNull() {
            addCriterion("memberid is not null");
            return (Criteria) this;
        }

        public Criteria andMemberidEqualTo(Integer value) {
            addCriterion("memberid =", value, "memberid");
            return (Criteria) this;
        }

        public Criteria andMemberidNotEqualTo(Integer value) {
            addCriterion("memberid <>", value, "memberid");
            return (Criteria) this;
        }

        public Criteria andMemberidGreaterThan(Integer value) {
            addCriterion("memberid >", value, "memberid");
            return (Criteria) this;
        }

        public Criteria andMemberidGreaterThanOrEqualTo(Integer value) {
            addCriterion("memberid >=", value, "memberid");
            return (Criteria) this;
        }

        public Criteria andMemberidLessThan(Integer value) {
            addCriterion("memberid <", value, "memberid");
            return (Criteria) this;
        }

        public Criteria andMemberidLessThanOrEqualTo(Integer value) {
            addCriterion("memberid <=", value, "memberid");
            return (Criteria) this;
        }

        public Criteria andMemberidIn(List<Integer> values) {
            addCriterion("memberid in", values, "memberid");
            return (Criteria) this;
        }

        public Criteria andMemberidNotIn(List<Integer> values) {
            addCriterion("memberid not in", values, "memberid");
            return (Criteria) this;
        }

        public Criteria andMemberidBetween(Integer value1, Integer value2) {
            addCriterion("memberid between", value1, value2, "memberid");
            return (Criteria) this;
        }

        public Criteria andMemberidNotBetween(Integer value1, Integer value2) {
            addCriterion("memberid not between", value1, value2, "memberid");
            return (Criteria) this;
        }

        public Criteria andOrderdateIsNull() {
            addCriterion("orderdate is null");
            return (Criteria) this;
        }

        public Criteria andOrderdateIsNotNull() {
            addCriterion("orderdate is not null");
            return (Criteria) this;
        }

        public Criteria andOrderdateEqualTo(Date value) {
            addCriterionForJDBCDate("orderdate =", value, "orderdate");
            return (Criteria) this;
        }

        public Criteria andOrderdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("orderdate <>", value, "orderdate");
            return (Criteria) this;
        }

        public Criteria andOrderdateGreaterThan(Date value) {
            addCriterionForJDBCDate("orderdate >", value, "orderdate");
            return (Criteria) this;
        }

        public Criteria andOrderdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("orderdate >=", value, "orderdate");
            return (Criteria) this;
        }

        public Criteria andOrderdateLessThan(Date value) {
            addCriterionForJDBCDate("orderdate <", value, "orderdate");
            return (Criteria) this;
        }

        public Criteria andOrderdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("orderdate <=", value, "orderdate");
            return (Criteria) this;
        }

        public Criteria andOrderdateIn(List<Date> values) {
            addCriterionForJDBCDate("orderdate in", values, "orderdate");
            return (Criteria) this;
        }

        public Criteria andOrderdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("orderdate not in", values, "orderdate");
            return (Criteria) this;
        }

        public Criteria andOrderdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("orderdate between", value1, value2, "orderdate");
            return (Criteria) this;
        }

        public Criteria andOrderdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("orderdate not between", value1, value2, "orderdate");
            return (Criteria) this;
        }

        public Criteria andReceviernameIsNull() {
            addCriterion("receviername is null");
            return (Criteria) this;
        }

        public Criteria andReceviernameIsNotNull() {
            addCriterion("receviername is not null");
            return (Criteria) this;
        }

        public Criteria andReceviernameEqualTo(String value) {
            addCriterion("receviername =", value, "receviername");
            return (Criteria) this;
        }

        public Criteria andReceviernameNotEqualTo(String value) {
            addCriterion("receviername <>", value, "receviername");
            return (Criteria) this;
        }

        public Criteria andReceviernameGreaterThan(String value) {
            addCriterion("receviername >", value, "receviername");
            return (Criteria) this;
        }

        public Criteria andReceviernameGreaterThanOrEqualTo(String value) {
            addCriterion("receviername >=", value, "receviername");
            return (Criteria) this;
        }

        public Criteria andReceviernameLessThan(String value) {
            addCriterion("receviername <", value, "receviername");
            return (Criteria) this;
        }

        public Criteria andReceviernameLessThanOrEqualTo(String value) {
            addCriterion("receviername <=", value, "receviername");
            return (Criteria) this;
        }

        public Criteria andReceviernameLike(String value) {
            addCriterion("receviername like", value, "receviername");
            return (Criteria) this;
        }

        public Criteria andReceviernameNotLike(String value) {
            addCriterion("receviername not like", value, "receviername");
            return (Criteria) this;
        }

        public Criteria andReceviernameIn(List<String> values) {
            addCriterion("receviername in", values, "receviername");
            return (Criteria) this;
        }

        public Criteria andReceviernameNotIn(List<String> values) {
            addCriterion("receviername not in", values, "receviername");
            return (Criteria) this;
        }

        public Criteria andReceviernameBetween(String value1, String value2) {
            addCriterion("receviername between", value1, value2, "receviername");
            return (Criteria) this;
        }

        public Criteria andReceviernameNotBetween(String value1, String value2) {
            addCriterion("receviername not between", value1, value2, "receviername");
            return (Criteria) this;
        }

        public Criteria andRecevierphoneIsNull() {
            addCriterion("recevierphone is null");
            return (Criteria) this;
        }

        public Criteria andRecevierphoneIsNotNull() {
            addCriterion("recevierphone is not null");
            return (Criteria) this;
        }

        public Criteria andRecevierphoneEqualTo(String value) {
            addCriterion("recevierphone =", value, "recevierphone");
            return (Criteria) this;
        }

        public Criteria andRecevierphoneNotEqualTo(String value) {
            addCriterion("recevierphone <>", value, "recevierphone");
            return (Criteria) this;
        }

        public Criteria andRecevierphoneGreaterThan(String value) {
            addCriterion("recevierphone >", value, "recevierphone");
            return (Criteria) this;
        }

        public Criteria andRecevierphoneGreaterThanOrEqualTo(String value) {
            addCriterion("recevierphone >=", value, "recevierphone");
            return (Criteria) this;
        }

        public Criteria andRecevierphoneLessThan(String value) {
            addCriterion("recevierphone <", value, "recevierphone");
            return (Criteria) this;
        }

        public Criteria andRecevierphoneLessThanOrEqualTo(String value) {
            addCriterion("recevierphone <=", value, "recevierphone");
            return (Criteria) this;
        }

        public Criteria andRecevierphoneLike(String value) {
            addCriterion("recevierphone like", value, "recevierphone");
            return (Criteria) this;
        }

        public Criteria andRecevierphoneNotLike(String value) {
            addCriterion("recevierphone not like", value, "recevierphone");
            return (Criteria) this;
        }

        public Criteria andRecevierphoneIn(List<String> values) {
            addCriterion("recevierphone in", values, "recevierphone");
            return (Criteria) this;
        }

        public Criteria andRecevierphoneNotIn(List<String> values) {
            addCriterion("recevierphone not in", values, "recevierphone");
            return (Criteria) this;
        }

        public Criteria andRecevierphoneBetween(String value1, String value2) {
            addCriterion("recevierphone between", value1, value2, "recevierphone");
            return (Criteria) this;
        }

        public Criteria andRecevierphoneNotBetween(String value1, String value2) {
            addCriterion("recevierphone not between", value1, value2, "recevierphone");
            return (Criteria) this;
        }

        public Criteria andReceiveraddressIsNull() {
            addCriterion("receiveraddress is null");
            return (Criteria) this;
        }

        public Criteria andReceiveraddressIsNotNull() {
            addCriterion("receiveraddress is not null");
            return (Criteria) this;
        }

        public Criteria andReceiveraddressEqualTo(String value) {
            addCriterion("receiveraddress =", value, "receiveraddress");
            return (Criteria) this;
        }

        public Criteria andReceiveraddressNotEqualTo(String value) {
            addCriterion("receiveraddress <>", value, "receiveraddress");
            return (Criteria) this;
        }

        public Criteria andReceiveraddressGreaterThan(String value) {
            addCriterion("receiveraddress >", value, "receiveraddress");
            return (Criteria) this;
        }

        public Criteria andReceiveraddressGreaterThanOrEqualTo(String value) {
            addCriterion("receiveraddress >=", value, "receiveraddress");
            return (Criteria) this;
        }

        public Criteria andReceiveraddressLessThan(String value) {
            addCriterion("receiveraddress <", value, "receiveraddress");
            return (Criteria) this;
        }

        public Criteria andReceiveraddressLessThanOrEqualTo(String value) {
            addCriterion("receiveraddress <=", value, "receiveraddress");
            return (Criteria) this;
        }

        public Criteria andReceiveraddressLike(String value) {
            addCriterion("receiveraddress like", value, "receiveraddress");
            return (Criteria) this;
        }

        public Criteria andReceiveraddressNotLike(String value) {
            addCriterion("receiveraddress not like", value, "receiveraddress");
            return (Criteria) this;
        }

        public Criteria andReceiveraddressIn(List<String> values) {
            addCriterion("receiveraddress in", values, "receiveraddress");
            return (Criteria) this;
        }

        public Criteria andReceiveraddressNotIn(List<String> values) {
            addCriterion("receiveraddress not in", values, "receiveraddress");
            return (Criteria) this;
        }

        public Criteria andReceiveraddressBetween(String value1, String value2) {
            addCriterion("receiveraddress between", value1, value2, "receiveraddress");
            return (Criteria) this;
        }

        public Criteria andReceiveraddressNotBetween(String value1, String value2) {
            addCriterion("receiveraddress not between", value1, value2, "receiveraddress");
            return (Criteria) this;
        }

        public Criteria andReceiverpostcodeIsNull() {
            addCriterion("receiverpostcode is null");
            return (Criteria) this;
        }

        public Criteria andReceiverpostcodeIsNotNull() {
            addCriterion("receiverpostcode is not null");
            return (Criteria) this;
        }

        public Criteria andReceiverpostcodeEqualTo(String value) {
            addCriterion("receiverpostcode =", value, "receiverpostcode");
            return (Criteria) this;
        }

        public Criteria andReceiverpostcodeNotEqualTo(String value) {
            addCriterion("receiverpostcode <>", value, "receiverpostcode");
            return (Criteria) this;
        }

        public Criteria andReceiverpostcodeGreaterThan(String value) {
            addCriterion("receiverpostcode >", value, "receiverpostcode");
            return (Criteria) this;
        }

        public Criteria andReceiverpostcodeGreaterThanOrEqualTo(String value) {
            addCriterion("receiverpostcode >=", value, "receiverpostcode");
            return (Criteria) this;
        }

        public Criteria andReceiverpostcodeLessThan(String value) {
            addCriterion("receiverpostcode <", value, "receiverpostcode");
            return (Criteria) this;
        }

        public Criteria andReceiverpostcodeLessThanOrEqualTo(String value) {
            addCriterion("receiverpostcode <=", value, "receiverpostcode");
            return (Criteria) this;
        }

        public Criteria andReceiverpostcodeLike(String value) {
            addCriterion("receiverpostcode like", value, "receiverpostcode");
            return (Criteria) this;
        }

        public Criteria andReceiverpostcodeNotLike(String value) {
            addCriterion("receiverpostcode not like", value, "receiverpostcode");
            return (Criteria) this;
        }

        public Criteria andReceiverpostcodeIn(List<String> values) {
            addCriterion("receiverpostcode in", values, "receiverpostcode");
            return (Criteria) this;
        }

        public Criteria andReceiverpostcodeNotIn(List<String> values) {
            addCriterion("receiverpostcode not in", values, "receiverpostcode");
            return (Criteria) this;
        }

        public Criteria andReceiverpostcodeBetween(String value1, String value2) {
            addCriterion("receiverpostcode between", value1, value2, "receiverpostcode");
            return (Criteria) this;
        }

        public Criteria andReceiverpostcodeNotBetween(String value1, String value2) {
            addCriterion("receiverpostcode not between", value1, value2, "receiverpostcode");
            return (Criteria) this;
        }

        public Criteria andReceiveremailsIsNull() {
            addCriterion("receiveremails is null");
            return (Criteria) this;
        }

        public Criteria andReceiveremailsIsNotNull() {
            addCriterion("receiveremails is not null");
            return (Criteria) this;
        }

        public Criteria andReceiveremailsEqualTo(String value) {
            addCriterion("receiveremails =", value, "receiveremails");
            return (Criteria) this;
        }

        public Criteria andReceiveremailsNotEqualTo(String value) {
            addCriterion("receiveremails <>", value, "receiveremails");
            return (Criteria) this;
        }

        public Criteria andReceiveremailsGreaterThan(String value) {
            addCriterion("receiveremails >", value, "receiveremails");
            return (Criteria) this;
        }

        public Criteria andReceiveremailsGreaterThanOrEqualTo(String value) {
            addCriterion("receiveremails >=", value, "receiveremails");
            return (Criteria) this;
        }

        public Criteria andReceiveremailsLessThan(String value) {
            addCriterion("receiveremails <", value, "receiveremails");
            return (Criteria) this;
        }

        public Criteria andReceiveremailsLessThanOrEqualTo(String value) {
            addCriterion("receiveremails <=", value, "receiveremails");
            return (Criteria) this;
        }

        public Criteria andReceiveremailsLike(String value) {
            addCriterion("receiveremails like", value, "receiveremails");
            return (Criteria) this;
        }

        public Criteria andReceiveremailsNotLike(String value) {
            addCriterion("receiveremails not like", value, "receiveremails");
            return (Criteria) this;
        }

        public Criteria andReceiveremailsIn(List<String> values) {
            addCriterion("receiveremails in", values, "receiveremails");
            return (Criteria) this;
        }

        public Criteria andReceiveremailsNotIn(List<String> values) {
            addCriterion("receiveremails not in", values, "receiveremails");
            return (Criteria) this;
        }

        public Criteria andReceiveremailsBetween(String value1, String value2) {
            addCriterion("receiveremails between", value1, value2, "receiveremails");
            return (Criteria) this;
        }

        public Criteria andReceiveremailsNotBetween(String value1, String value2) {
            addCriterion("receiveremails not between", value1, value2, "receiveremails");
            return (Criteria) this;
        }

        public Criteria andIsconfirmIsNull() {
            addCriterion("isconfirm is null");
            return (Criteria) this;
        }

        public Criteria andIsconfirmIsNotNull() {
            addCriterion("isconfirm is not null");
            return (Criteria) this;
        }

        public Criteria andIsconfirmEqualTo(Byte value) {
            addCriterion("isconfirm =", value, "isconfirm");
            return (Criteria) this;
        }

        public Criteria andIsconfirmNotEqualTo(Byte value) {
            addCriterion("isconfirm <>", value, "isconfirm");
            return (Criteria) this;
        }

        public Criteria andIsconfirmGreaterThan(Byte value) {
            addCriterion("isconfirm >", value, "isconfirm");
            return (Criteria) this;
        }

        public Criteria andIsconfirmGreaterThanOrEqualTo(Byte value) {
            addCriterion("isconfirm >=", value, "isconfirm");
            return (Criteria) this;
        }

        public Criteria andIsconfirmLessThan(Byte value) {
            addCriterion("isconfirm <", value, "isconfirm");
            return (Criteria) this;
        }

        public Criteria andIsconfirmLessThanOrEqualTo(Byte value) {
            addCriterion("isconfirm <=", value, "isconfirm");
            return (Criteria) this;
        }

        public Criteria andIsconfirmIn(List<Byte> values) {
            addCriterion("isconfirm in", values, "isconfirm");
            return (Criteria) this;
        }

        public Criteria andIsconfirmNotIn(List<Byte> values) {
            addCriterion("isconfirm not in", values, "isconfirm");
            return (Criteria) this;
        }

        public Criteria andIsconfirmBetween(Byte value1, Byte value2) {
            addCriterion("isconfirm between", value1, value2, "isconfirm");
            return (Criteria) this;
        }

        public Criteria andIsconfirmNotBetween(Byte value1, Byte value2) {
            addCriterion("isconfirm not between", value1, value2, "isconfirm");
            return (Criteria) this;
        }

        public Criteria andIspaymentIsNull() {
            addCriterion("ispayment is null");
            return (Criteria) this;
        }

        public Criteria andIspaymentIsNotNull() {
            addCriterion("ispayment is not null");
            return (Criteria) this;
        }

        public Criteria andIspaymentEqualTo(Byte value) {
            addCriterion("ispayment =", value, "ispayment");
            return (Criteria) this;
        }

        public Criteria andIspaymentNotEqualTo(Byte value) {
            addCriterion("ispayment <>", value, "ispayment");
            return (Criteria) this;
        }

        public Criteria andIspaymentGreaterThan(Byte value) {
            addCriterion("ispayment >", value, "ispayment");
            return (Criteria) this;
        }

        public Criteria andIspaymentGreaterThanOrEqualTo(Byte value) {
            addCriterion("ispayment >=", value, "ispayment");
            return (Criteria) this;
        }

        public Criteria andIspaymentLessThan(Byte value) {
            addCriterion("ispayment <", value, "ispayment");
            return (Criteria) this;
        }

        public Criteria andIspaymentLessThanOrEqualTo(Byte value) {
            addCriterion("ispayment <=", value, "ispayment");
            return (Criteria) this;
        }

        public Criteria andIspaymentIn(List<Byte> values) {
            addCriterion("ispayment in", values, "ispayment");
            return (Criteria) this;
        }

        public Criteria andIspaymentNotIn(List<Byte> values) {
            addCriterion("ispayment not in", values, "ispayment");
            return (Criteria) this;
        }

        public Criteria andIspaymentBetween(Byte value1, Byte value2) {
            addCriterion("ispayment between", value1, value2, "ispayment");
            return (Criteria) this;
        }

        public Criteria andIspaymentNotBetween(Byte value1, Byte value2) {
            addCriterion("ispayment not between", value1, value2, "ispayment");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_OrderInfo
     *
     * @mbg.generated do_not_delete_during_merge Mon May 29 15:39:24 GMT+08:00 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_OrderInfo
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}