package cn.com.fangself.generator.mybatis.model.pojo;

public class ShopCart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ShopCart.cartid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    private Integer cartid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ShopCart.cartuuid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    private String cartuuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ShopCart.buyid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    private Integer buyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ShopCart.memberid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    private Integer memberid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ShopCart.totalprice
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    private Double totalprice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ShopCart.cartid
     *
     * @return the value of tb_ShopCart.cartid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public Integer getCartid() {
        return cartid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ShopCart.cartid
     *
     * @param cartid the value for tb_ShopCart.cartid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setCartid(Integer cartid) {
        this.cartid = cartid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ShopCart.cartuuid
     *
     * @return the value of tb_ShopCart.cartuuid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public String getCartuuid() {
        return cartuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ShopCart.cartuuid
     *
     * @param cartuuid the value for tb_ShopCart.cartuuid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setCartuuid(String cartuuid) {
        this.cartuuid = cartuuid == null ? null : cartuuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ShopCart.buyid
     *
     * @return the value of tb_ShopCart.buyid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public Integer getBuyid() {
        return buyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ShopCart.buyid
     *
     * @param buyid the value for tb_ShopCart.buyid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setBuyid(Integer buyid) {
        this.buyid = buyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ShopCart.memberid
     *
     * @return the value of tb_ShopCart.memberid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public Integer getMemberid() {
        return memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ShopCart.memberid
     *
     * @param memberid the value for tb_ShopCart.memberid
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setMemberid(Integer memberid) {
        this.memberid = memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ShopCart.totalprice
     *
     * @return the value of tb_ShopCart.totalprice
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public Double getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ShopCart.totalprice
     *
     * @param totalprice the value for tb_ShopCart.totalprice
     *
     * @mbg.generated Mon May 29 15:39:24 GMT+08:00 2017
     */
    public void setTotalprice(Double totalprice) {
        this.totalprice = totalprice;
    }
}